name: brager
description: "Free Music. No Ads. For Everyone."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # Audio
  just_audio: ^0.9.40
  audio_service: ^0.18.12

  # Icons
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Network images with caching
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

  # Dominant color extraction from album art (Spotify-style backgrounds)
  palette_generator: ^0.3.3

  # HTTP client
  dio: ^5.4.3

  # Local storage
  shared_preferences: ^2.2.3

  # SVG support
  flutter_svg: ^2.0.10+1

  # Smooth page transitions
  page_transition: ^2.1.0

  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: any
  ffi: ^2.1.0
  just_waveform: ^0.0.7
  path_provider: ^2.1.4
  path: ^1.9.0

  # Local database
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  share_plus: ^13.3.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/nyx_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/nyx_logo.png"
  remove_alpha_ios: true
  background_color_ios: "#000000"
  web:
    generate: true
    image_path: "assets/icons/nyx_logo.png"
    background_color: "#111111"
    theme_color: "#111111"
  windows:
    generate: true
    image_path: "assets/icons/nyx_logo.png"
  macos:
    generate: true
    image_path: "assets/icons/nyx_logo.png"

flutter_native_splash:
  color: "#111111"
  image: "assets/icons/nyx_logo.png"
  android_12:
    color: "#111111"
    image: "assets/icons/nyx_logo.png"
  web: false
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/lyrics/
    - assets/fonts/ibm-plex-sans/complete/ttf/
    - assets/fonts/ibm-plex-mono/fonts/complete/ttf/
    - assets/fonts/cairo/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/ibm-plex-sans/complete/ttf/IBM Plex Sans Var-Roman.ttf

    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/ibm-plex-mono/fonts/complete/ttf/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/ibm-plex-mono/fonts/complete/ttf/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm-plex-mono/fonts/complete/ttf/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm-plex-mono/fonts/complete/ttf/IBMPlexMono-Bold.ttf
          weight: 700

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Variable.ttf
